import type { HomeDashboardViewModel } from "@/features/learning/types/dashboard.types";
import { yamaService } from "@/features/yama/services/yama.service";

/**
 * Phase 0 placeholder data only.
 * Replace with database/CMS content via dashboard.service.ts when backend is connected.
 */
export const PLACEHOLDER_HOME_DASHBOARD: HomeDashboardViewModel = {
  greeting: "Konnichiwa, Climber",
  region: {
    slug: "n4",
    name: "Mount N4",
    trail: "Forest Trail",
  },
  level: {
    label: "N4",
    progressPercent: 41,
  },
  elevation: {
    level: 1,
    totalEp: 1240,
    currentEp: 40,
    epToNextLevel: 100,
    progressPercent: 40,
    activeTitle: "Base Camper",
    nextMilestone: "Level 2: Trail Walker",
  },
  quests: {
    daily: {
      questDate: "2026-06-10",
      completedCount: 1,
      totalCount: 4,
      quests: [
        {
          id: "quest-1",
          slug: "learn-vocabulary",
          title: "Learn 10 Words",
          description: "Learn 10 new vocabulary items today.",
          current: 6,
          target: 10,
          completed: false,
          epReward: 50,
          href: "/tree",
          progressPercent: 60,
        },
        {
          id: "quest-2",
          slug: "complete-lessons",
          title: "Complete 2 Lessons",
          description: "Finish 2 full lessons today.",
          current: 2,
          target: 2,
          completed: true,
          epReward: 75,
          href: "/tree",
          progressPercent: 100,
        },
        {
          id: "quest-3",
          slug: "review-items",
          title: "Review 20 Items",
          description: "Complete 20 SRS review ratings today.",
          current: 12,
          target: 20,
          completed: false,
          epReward: 75,
          href: "/review",
          progressPercent: 60,
        },
        {
          id: "quest-4",
          slug: "earn-ep",
          title: "Earn 100 EP",
          description: "Gain 100 elevation points from learning today.",
          current: 45,
          target: 100,
          completed: false,
          epReward: 100,
          href: "/tree",
          progressPercent: 45,
        },
      ],
    },
    weekly: {
      weekStart: "2026-06-08",
      completedCount: 0,
      totalCount: 2,
      quests: [
        {
          id: "quest-w1",
          slug: "weekly-complete-lessons",
          title: "Weekly Climber",
          description: "Complete 5 lessons this week.",
          current: 2,
          target: 5,
          completed: false,
          epReward: 150,
          href: "/tree",
          progressPercent: 40,
        },
        {
          id: "quest-w2",
          slug: "weekly-review-items",
          title: "Weekly Reviewer",
          description: "Complete 100 review ratings this week.",
          current: 12,
          target: 100,
          completed: false,
          epReward: 150,
          href: "/review",
          progressPercent: 12,
        },
      ],
    },
  },
  journeyPreview: [
    {
      id: "lesson-1",
      lessonId: "lesson-1",
      kind: "checkpoint",
      label: "Hiragana: a, i, u",
      subtitle: "Exam · 25 XP",
      lessonType: "checkpoint",
      state: "completed",
      pathPosition: 0.17,
      regionIndex: 0,
      globalIndex: 0,
      href: "/tree",
      xpReward: 25,
    },
    {
      id: "lesson-2",
      lessonId: "lesson-2",
      kind: "lesson",
      label: "Hiragana: e, o",
      subtitle: "hiragana · 10 XP",
      lessonType: "hiragana",
      state: "in_progress",
      pathPosition: 0.5,
      regionIndex: 1,
      globalIndex: 1,
      href: "/tree",
      xpReward: 10,
    },
    {
      id: "lesson-3",
      lessonId: "lesson-3",
      kind: "lesson",
      label: "Hiragana: ka, ki",
      subtitle: "hiragana · 10 XP",
      lessonType: "hiragana",
      state: "locked",
      pathPosition: 0.83,
      regionIndex: 2,
      globalIndex: 2,
      href: null,
      xpReward: 10,
    },
  ],
  currentJourneyNodeId: "lesson-2",
  upcomingLesson: {
    title: "Lesson 23: ~て form",
    href: "/tree",
    lessonNumber: 7,
    lessonCount: 20,
    estimatedDuration: 4,
  },
  stats: {
    currentStreak: 12,
    totalXp: 1250,
  },
  recentAchievements: [
    { id: "first-step", slug: "first-step", title: "First Step", rarity: "common" },
    {
      id: "ten-lessons",
      slug: "ten-lessons",
      title: "Trail Walker",
      rarity: "uncommon",
    },
  ],
  reviewQueueCount: 8,
  readyTrial: null,
  gamesAvailable: false,
  companion: {
    bondLevel: 3,
    bondXp: 250,
    bondXpToNextLevel: 50,
    progressPercent: 50,
    evolutionSlug: "young_fox",
    evolutionName: "Young Fox",
    equippedOutfitName: null,
  },
  progressionPreview: {
    unlocks: [],
    primaryUnlock: null,
  },
  dailyGoal: {
    targetMinutes: 15,
    progressPercent: 25,
    label: "1/4 daily quests",
  },
  chests: [],
  shrineProtection: {
    tokensAvailable: 0,
    tokensUsed: 0,
  },
  yama: yamaService.resolveHomePresence(
    {
      dailyQuestsCompleted: 1,
      dailyQuestsTotal: 4,
      regionProgressPercent: 41,
      hasInProgressTrailNode: true,
    },
    0,
  ),
};
