rows = [
    ("ア", "a", "a", "A row (ア行)", 0, "base"),
    ("イ", "i", "a", "A row (ア行)", 1, "base"),
    ("ウ", "u", "a", "A row (ア行)", 2, "base"),
    ("エ", "e", "a", "A row (ア行)", 3, "base"),
    ("オ", "o", "a", "A row (ア行)", 4, "base"),
    ("カ", "ka", "ka", "Ka row (カ行)", 5, "base"),
    ("キ", "ki", "ka", "Ka row (カ行)", 6, "base"),
    ("ク", "ku", "ka", "Ka row (カ行)", 7, "base"),
    ("ケ", "ke", "ka", "Ka row (カ行)", 8, "base"),
    ("コ", "ko", "ka", "Ka row (カ行)", 9, "base"),
    ("サ", "sa", "sa", "Sa row (サ行)", 10, "base"),
    ("シ", "shi", "sa", "Sa row (サ行)", 11, "base"),
    ("ス", "su", "sa", "Sa row (サ行)", 12, "base"),
    ("セ", "se", "sa", "Sa row (サ行)", 13, "base"),
    ("ソ", "so", "sa", "Sa row (サ行)", 14, "base"),
    ("タ", "ta", "ta", "Ta row (タ行)", 15, "base"),
    ("チ", "chi", "ta", "Ta row (タ行)", 16, "base"),
    ("ツ", "tsu", "ta", "Ta row (タ行)", 17, "base"),
    ("テ", "te", "ta", "Ta row (タ行)", 18, "base"),
    ("ト", "to", "ta", "Ta row (タ行)", 19, "base"),
    ("ナ", "na", "na", "Na row (ナ行)", 20, "base"),
    ("ニ", "ni", "na", "Na row (ナ行)", 21, "base"),
    ("ヌ", "nu", "na", "Na row (ナ行)", 22, "base"),
    ("ネ", "ne", "na", "Na row (ナ行)", 23, "base"),
    ("ノ", "no", "na", "Na row (ナ行)", 24, "base"),
    ("ハ", "ha", "ha", "Ha row (ハ行)", 25, "base"),
    ("ヒ", "hi", "ha", "Ha row (ハ行)", 26, "base"),
    ("フ", "fu", "ha", "Ha row (ハ行)", 27, "base"),
    ("ヘ", "he", "ha", "Ha row (ハ行)", 28, "base"),
    ("ホ", "ho", "ha", "Ha row (ハ行)", 29, "base"),
    ("マ", "ma", "ma", "Ma row (マ行)", 30, "base"),
    ("ミ", "mi", "ma", "Ma row (マ行)", 31, "base"),
    ("ム", "mu", "ma", "Ma row (マ行)", 32, "base"),
    ("メ", "me", "ma", "Ma row (マ行)", 33, "base"),
    ("モ", "mo", "ma", "Ma row (マ行)", 34, "base"),
    ("ヤ", "ya", "ya", "Ya row (ヤ行)", 35, "base"),
    ("ユ", "yu", "ya", "Ya row (ヤ行)", 36, "base"),
    ("ヨ", "yo", "ya", "Ya row (ヤ行)", 37, "base"),
    ("ラ", "ra", "ra", "Ra row (ラ行)", 38, "base"),
    ("リ", "ri", "ra", "Ra row (ラ行)", 39, "base"),
    ("ル", "ru", "ra", "Ra row (ラ行)", 40, "base"),
    ("レ", "re", "ra", "Ra row (ラ行)", 41, "base"),
    ("ロ", "ro", "ra", "Ra row (ラ行)", 42, "base"),
    ("ワ", "wa", "wa", "Wa row (ワ行)", 43, "base"),
    ("ヲ", "wo", "wa", "Wa row (ワ行)", 44, "base"),
    ("ン", "n", "n", "N (ン)", 45, "base"),
    ("ガ", "ga", "voiced", "Voiced (濁音)", 46, "dakuten"),
    ("ギ", "gi", "voiced", "Voiced (濁音)", 47, "dakuten"),
    ("グ", "gu", "voiced", "Voiced (濁音)", 48, "dakuten"),
    ("ゲ", "ge", "voiced", "Voiced (濁音)", 49, "dakuten"),
    ("ゴ", "go", "voiced", "Voiced (濁音)", 50, "dakuten"),
    ("ザ", "za", "voiced", "Voiced (濁音)", 51, "dakuten"),
    ("ジ", "ji", "voiced", "Voiced (濁音)", 52, "dakuten"),
    ("ズ", "zu", "voiced", "Voiced (濁音)", 53, "dakuten"),
    ("ゼ", "ze", "voiced", "Voiced (濁音)", 54, "dakuten"),
    ("ゾ", "zo", "voiced", "Voiced (濁音)", 55, "dakuten"),
    ("ダ", "da", "voiced", "Voiced (濁音)", 56, "dakuten"),
    ("ヂ", "ji", "voiced", "Voiced (濁音)", 57, "dakuten"),
    ("ヅ", "zu", "voiced", "Voiced (濁音)", 58, "dakuten"),
    ("デ", "de", "voiced", "Voiced (濁音)", 59, "dakuten"),
    ("ド", "do", "voiced", "Voiced (濁音)", 60, "dakuten"),
    ("バ", "ba", "voiced", "Voiced (濁音)", 61, "dakuten"),
    ("ビ", "bi", "voiced", "Voiced (濁音)", 62, "dakuten"),
    ("ブ", "bu", "voiced", "Voiced (濁音)", 63, "dakuten"),
    ("ベ", "be", "voiced", "Voiced (濁音)", 64, "dakuten"),
    ("ボ", "bo", "voiced", "Voiced (濁音)", 65, "dakuten"),
    ("パ", "pa", "semiVoiced", "Semi-voiced (半濁音)", 66, "handakuten"),
    ("ピ", "pi", "semiVoiced", "Semi-voiced (半濁音)", 67, "handakuten"),
    ("プ", "pu", "semiVoiced", "Semi-voiced (半濁音)", 68, "handakuten"),
    ("ペ", "pe", "semiVoiced", "Semi-voiced (半濁音)", 69, "handakuten"),
    ("ポ", "po", "semiVoiced", "Semi-voiced (半濁音)", 70, "handakuten"),
    ("キャ", "kya", "combo", "Combinations (拗音)", 71, "combo"),
    ("キュ", "kyu", "combo", "Combinations (拗音)", 72, "combo"),
    ("キョ", "kyo", "combo", "Combinations (拗音)", 73, "combo"),
    ("シャ", "sha", "combo", "Combinations (拗音)", 74, "combo"),
    ("シュ", "shu", "combo", "Combinations (拗音)", 75, "combo"),
    ("ショ", "sho", "combo", "Combinations (拗音)", 76, "combo"),
    ("チャ", "cha", "combo", "Combinations (拗音)", 77, "combo"),
    ("チュ", "chu", "combo", "Combinations (拗音)", 78, "combo"),
    ("チョ", "cho", "combo", "Combinations (拗音)", 79, "combo"),
    ("ニャ", "nya", "combo", "Combinations (拗音)", 80, "combo"),
    ("ニュ", "nyu", "combo", "Combinations (拗音)", 81, "combo"),
    ("ニョ", "nyo", "combo", "Combinations (拗音)", 82, "combo"),
    ("ヒャ", "hya", "combo", "Combinations (拗音)", 83, "combo"),
    ("ヒュ", "hyu", "combo", "Combinations (拗音)", 84, "combo"),
    ("ヒョ", "hyo", "combo", "Combinations (拗音)", 85, "combo"),
    ("ミャ", "mya", "combo", "Combinations (拗音)", 86, "combo"),
    ("ミュ", "myu", "combo", "Combinations (拗音)", 87, "combo"),
    ("ミョ", "myo", "combo", "Combinations (拗音)", 88, "combo"),
    ("リャ", "rya", "combo", "Combinations (拗音)", 89, "combo"),
    ("リュ", "ryu", "combo", "Combinations (拗音)", 90, "combo"),
    ("リョ", "ryo", "combo", "Combinations (拗音)", 91, "combo"),
    ("ギャ", "gya", "combo", "Combinations (拗音)", 92, "combo"),
    ("ギュ", "gyu", "combo", "Combinations (拗音)", 93, "combo"),
    ("ギョ", "gyo", "combo", "Combinations (拗音)", 94, "combo"),
    ("ジャ", "ja", "combo", "Combinations (拗音)", 95, "combo"),
    ("ジュ", "ju", "combo", "Combinations (拗音)", 96, "combo"),
    ("ジョ", "jo", "combo", "Combinations (拗音)", 97, "combo"),
    ("ビャ", "bya", "combo", "Combinations (拗音)", 98, "combo"),
    ("ビュ", "byu", "combo", "Combinations (拗音)", 99, "combo"),
    ("ビョ", "byo", "combo", "Combinations (拗音)", 100, "combo"),
    ("ピャ", "pya", "combo", "Combinations (拗音)", 101, "combo"),
    ("ピュ", "pyu", "combo", "Combinations (拗音)", 102, "combo"),
    ("ピョ", "pyo", "combo", "Combinations (拗音)", 103, "combo"),
]

for character, romaji, row_name, row_label, order_index, variant_type in rows:
    print(
        f"    ('{character}', '{romaji}', '{row_name}', '{row_label}', {order_index}, '{variant_type}'),"
    )
