"""JLPT N5 target vocabulary bank — used by build-n5-vocabulary-completion.py."""

from __future__ import annotations

Word = tuple[str, str, str, str, str, str, str]


def w(
    kana: str,
    kanji: str,
    meaning: str,
    pos: str,
    jp: str,
    romaji: str,
    en: str,
) -> Word:
    return (kana, kanji, meaning, pos, jp, romaji, en)


def weekdays() -> list[Word]:
    days = [
        ("かようび", "火曜日", "Tuesday"),
        ("すいようび", "水曜日", "Wednesday"),
        ("もくようび", "木曜日", "Thursday"),
        ("きんようび", "金曜日", "Friday"),
        ("どようび", "土曜日", "Saturday"),
        ("にちようび", "日曜日", "Sunday"),
    ]
    return [
        w(k, kj, m, "noun", f"{kj}は忙しいです。", f"{kj} wa isogashii desu.", f"{m} is busy.")
        for k, kj, m in days
    ]


def months() -> list[Word]:
    items = [
        ("いちがつ", "一月", "January"),
        ("にがつ", "二月", "February"),
        ("さんがつ", "三月", "March"),
        ("しがつ", "四月", "April"),
        ("ごがつ", "五月", "May"),
        ("ろくがつ", "六月", "June"),
        ("しちがつ", "七月", "July"),
        ("はちがつ", "八月", "August"),
        ("くがつ", "九月", "September"),
        ("じゅうがつ", "十月", "October"),
        ("じゅういちがつ", "十一月", "November"),
        ("じゅうにがつ", "十二月", "December"),
    ]
    return [
        w(k, kj, m, "noun", f"{kj}に旅行します。", f"{kj} ni ryokou shimasu.", f"I travel in {m}.")
        for k, kj, m in items
    ]


CURATED: list[Word] = [
    # Identity & people
    w("なまえ", "名前", "name", "noun", "名前は何ですか。", "Namae wa nan desu ka.", "What is your name?"),
    w("じゅうしょ", "住所", "address", "noun", "住所を教えてください。", "Juusho o oshiete kudasai.", "Please tell me your address."),
    w("でんわばんごう", "電話番号", "phone number", "noun", "電話番号を教えてください。", "Denwa bangou o oshiete kudasai.", "Please tell me your phone number."),
    w("とし", "年", "year, age", "noun", "今年は二十歳です。", "Kotoshi wa hatachi desu.", "I am twenty this year."),
    w("さい", "歳", "years old", "noun", "私は二十歳です。", "Watashi wa hatachi desu.", "I am twenty years old."),
    w("たんじょうび", "誕生日", "birthday", "noun", "誕生日はいつですか。", "Tanjoubi wa itsu desu ka.", "When is your birthday?"),
    w("けっこん", "結婚", "marriage", "noun", "結婚しました。", "Kekkon shimashita.", "I got married."),
    w("こども", "子供", "child", "noun", "子供が二人います。", "Kodomo ga futari imasu.", "I have two children."),
    w("おとな", "大人", "adult", "noun", "大人は五百円です。", "Otona wa gohyaku en desu.", "Adults are five hundred yen."),
    w("わかもの", "若者", "young person", "noun", "若者が多いです。", "Wakamono ga ooi desu.", "There are many young people."),
    # Home & rooms
    w("まど", "窓", "window", "noun", "窓を開けます。", "Mado o akemasu.", "I open the window."),
    w("かべ", "壁", "wall", "noun", "壁は白いです。", "Kabe wa shiroi desu.", "The wall is white."),
    w("ゆか", "床", "floor", "noun", "床を掃除します。", "Yuka o souji shimasu.", "I clean the floor."),
    w("やね", "屋根", "roof", "noun", "屋根が高いです。", "Yane ga takai desu.", "The roof is high."),
    w("かい", "階", "floor (level)", "noun", "三階にあります。", "Sankai ni arimasu.", "It is on the third floor."),
    w("おくじょう", "屋上", "rooftop", "noun", "屋上へ行きます。", "Okujou e ikimasu.", "I go to the rooftop."),
    w("げんかん", "玄関", "entrance", "noun", "玄関で靴を脱ぎます。", "Genkan de kutsu o nugimasu.", "I take off shoes at the entrance."),
    w("ふろば", "風呂場", "bathroom", "noun", "風呂場を掃除します。", "Furoba o souji shimasu.", "I clean the bathroom."),
    w("せんめんじょ", "洗面所", "washroom", "noun", "洗面所で歯を磨きます。", "Senmenjo de ha o migakimasu.", "I brush my teeth in the washroom."),
    w("しょうめい", "照明", "lighting", "noun", "照明をつけます。", "Shoumei o tsukemasu.", "I turn on the lighting."),
    # Travel & transport
    w("くうこう", "空港", "airport", "noun", "空港へ行きます。", "Kuukou e ikimasu.", "I go to the airport."),
    w("しゅっぱつ", "出発", "departure", "noun", "出発は九時です。", "Shuppatsu wa kuji desu.", "Departure is at nine."),
    w("とうちゃく", "到着", "arrival", "noun", "到着は午後です。", "Touchaku wa gogo desu.", "Arrival is in the afternoon."),
    w("のりかえ", "乗り換え", "transfer", "noun", "駅で乗り換えます。", "Eki de norikaemasu.", "I transfer at the station."),
    w("ざせき", "座席", "seat", "noun", "座席を予約します。", "Zaseki o yoyaku shimasu.", "I reserve a seat."),
    w("きっぷうりば", "切符売り場", "ticket counter", "noun", "切符売り場はどこですか。", "Kippu uriba wa doko desu ka.", "Where is the ticket counter?"),
    w("ホーム", "", "platform", "noun", "ホームで待ちます。", "Hoomu de machimasu.", "I wait on the platform."),
    w("かいさつ", "改札", "ticket gate", "noun", "改札を通ります。", "Kaisatsu o toorimasu.", "I pass through the ticket gate."),
    w("りょこうかばん", "旅行かばん", "suitcase", "noun", "旅行かばんを持ちます。", "Ryokou kaban o mochimasu.", "I carry a suitcase."),
    w("パスポート", "", "passport", "noun", "パスポートを見せます。", "Pasupooto o misemasu.", "I show my passport."),
    # Body extended
    w("は", "歯", "tooth", "noun", "歯を磨きます。", "Ha o migakimasu.", "I brush my teeth."),
    w("かた", "肩", "shoulder", "noun", "肩が痛いです。", "Kata ga itai desu.", "My shoulder hurts."),
    w("くび", "首", "neck", "noun", "首が回りません。", "Kubi ga mawarimasen.", "My neck won't turn."),
    w("むね", "胸", "chest", "noun", "胸が痛いです。", "Mune ga itai desu.", "My chest hurts."),
    w("おなか", "お腹", "stomach", "noun", "お腹が空きました。", "Onaka ga sukimashita.", "I am hungry."),
    w("せなか", "背中", "back (body)", "noun", "背中が痛いです。", "Senaka ga itai desu.", "My back hurts."),
    w("ひざ", "膝", "knee", "noun", "膝を曲げます。", "Hiza o magemasu.", "I bend my knee."),
    w("けが", "怪我", "injury", "noun", "怪我をしました。", "Kega o shimashita.", "I was injured."),
    w("ちゅうしゃ", "注射", "injection", "noun", "注射は痛いです。", "Chuusha wa itai desu.", "The injection hurts."),
    w("けんこう", "健康", "health", "noun", "健康が大事です。", "Kenkou ga daiji desu.", "Health is important."),
    # Language & study
    w("いみ", "意味", "meaning", "noun", "意味が分かりません。", "Imi ga wakarimasen.", "I do not understand the meaning."),
    w("ことば", "言葉", "word, language", "noun", "新しい言葉を覚えます。", "Atarashii kotoba o oboemasu.", "I memorize new words."),
    w("かいわ", "会話", "conversation", "noun", "会話を練習します。", "Kaiwa o renshuu shimasu.", "I practice conversation."),
    w("ぶん", "文", "sentence", "noun", "文を作ります。", "Bun o tsukurimasu.", "I make a sentence."),
    w("ぶんしょう", "文章", "text, passage", "noun", "文章を読みます。", "Bunshou o yomimasu.", "I read a passage."),
    w("ひらがな", "ひらがな", "hiragana", "noun", "ひらがなを書きます。", "Hiragana o kakimasu.", "I write hiragana."),
    w("カタカナ", "カタカナ", "katakana", "noun", "カタカナを練習します。", "Katakana o renshuu shimasu.", "I practice katakana."),
    w("はつおん", "発音", "pronunciation", "noun", "発音が難しいです。", "Hatsuon ga muzukashii desu.", "Pronunciation is difficult."),
    w("ふくしゅう", "復習", "review", "noun", "復習をします。", "Fukushuu o shimasu.", "I do review."),
    w("よしゅう", "予習", "preparation (study)", "noun", "予習をします。", "Yoshuu o shimasu.", "I prepare for class."),
    w("しつもん", "質問", "question", "noun", "質問があります。", "Shitsumon ga arimasu.", "I have a question."),
    w("こたえ", "答え", "answer", "noun", "答えを書きます。", "Kotae o kakimasu.", "I write the answer."),
    w("もんだい", "問題", "problem, question", "noun", "問題を解きます。", "Mondai o tokimasu.", "I solve the problem."),
    w("ごうかく", "合格", "passing (exam)", "noun", "合格しました。", "Goukaku shimashita.", "I passed."),
    w("ふごうかく", "不合格", "failing (exam)", "noun", "不合格でした。", "Fugoukaku deshita.", "I failed."),
    w("てん", "点", "point, score", "noun", "百点を取りました。", "Hyakuten o torimashita.", "I got a hundred points."),
    w("ばんごう", "番号", "number", "noun", "番号を教えてください。", "Bangou o oshiete kudasai.", "Please tell me the number."),
    # Verbs — core gaps
    w("はじめる", "始める", "to begin", "verb", "勉強を始めます。", "Benkyou o hajimemasu.", "I begin studying."),
    w("おわる", "終わる", "to end", "verb", "授業が終わります。", "Jugyou ga owarimasu.", "Class ends."),
    w("つづける", "続ける", "to continue", "verb", "練習を続けます。", "Renshuu o tsuzukemasu.", "I continue practicing."),
    w("とめる", "止める", "to stop", "verb", "車を止めます。", "Kuruma o tomemasu.", "I stop the car."),
    w("なる", "なる", "to become", "verb", "先生になります。", "Sensei ni narimasu.", "I become a teacher."),
    w("しぬ", "死ぬ", "to die", "verb", "魚が死にました。", "Sakana ga shinimashita.", "The fish died."),
    w("いきる", "生きる", "to live", "verb", "日本で生きます。", "Nihon de ikimasu.", "I live in Japan."),
    w("うまれる", "生まれる", "to be born", "verb", "日本で生まれました。", "Nihon de umaremashita.", "I was born in Japan."),
    w("きる", "着る", "to wear (upper body)", "verb", "シャツを着ます。", "Shatsu o kimasu.", "I wear a shirt."),
    w("ぬぐ", "脱ぐ", "to take off (clothes)", "verb", "靴を脱ぎます。", "Kutsu o nugimasu.", "I take off my shoes."),
    w("かぶる", "被る", "to wear (on head)", "verb", "帽子を被ります。", "Boushi o kaburimasu.", "I wear a hat."),
    w("はく", "履く", "to wear (lower body, shoes)", "verb", "ズボンを履きます。", "Zubon o hakimasu.", "I put on pants."),
    w("みがく", "磨く", "to polish, brush", "verb", "歯を磨きます。", "Ha o migakimasu.", "I brush my teeth."),
    w("ふく", "拭く", "to wipe", "verb", "テーブルを拭きます。", "Teeburu o fukimasu.", "I wipe the table."),
    w("かたづける", "片付ける", "to tidy up", "verb", "部屋を片付けます。", "Heya o katazukemasu.", "I tidy the room."),
    w("ならべる", "並べる", "to line up, arrange", "verb", "本を並べます。", "Hon o narabemasu.", "I line up the books."),
    w("あつまる", "集まる", "to gather", "verb", "友達が集まります。", "Tomodachi ga atsumarimasu.", "Friends gather."),
    w("むかえる", "迎える", "to welcome, pick up", "verb", "駅で迎えます。", "Eki de mukaemasu.", "I pick someone up at the station."),
    w("おくる", "送る", "to send", "verb", "手紙を送ります。", "Tegami o okurimasu.", "I send a letter."),
    w("ひく", "引く", "to pull", "verb", "ドアを引きます。", "Doa o hikimasu.", "I pull the door."),
    w("おす", "押す", "to push", "verb", "ボタンを押します。", "Botan o oshimasu.", "I push the button."),
    w("おとす", "落とす", "to drop", "verb", "財布を落としました。", "Saifu o otoshimashita.", "I dropped my wallet."),
    w("ひろう", "拾う", "to pick up", "verb", "落ちた物を拾います。", "Ochita mono o hiromasu.", "I pick up the dropped item."),
    w("わたす", "渡す", "to hand over", "verb", "本を渡します。", "Hon o watashimasu.", "I hand over the book."),
    w("かす", "貸す", "to lend", "verb", "本を貸します。", "Hon o kashimasu.", "I lend a book."),
    w("かりる", "借りる", "to borrow", "verb", "本を借ります。", "Hon o karimasu.", "I borrow a book."),
    w("かえす", "返す", "to return (item)", "verb", "本を返します。", "Hon o kaeshimasu.", "I return the book."),
    w("つかれる", "疲れる", "to get tired", "verb", "疲れました。", "Tsukaremashita.", "I got tired."),
    w("こわれる", "壊れる", "to break", "verb", "時計が壊れました。", "Tokei ga kowaremashita.", "The watch broke."),
    w("ぬれる", "濡れる", "to get wet", "verb", "雨で濡れました。", "Ame de nuremashita.", "I got wet in the rain."),
    # Adjectives & adverbs
    w("しずか", "静か", "quiet", "na-adjective", "図書館は静かです。", "Toshokan wa shizuka desu.", "The library is quiet."),
    w("にぎやか", "賑やか", "lively, bustling", "na-adjective", "町は賑やかです。", "Machi wa nigiyaka desu.", "The town is lively."),
    w("ゆうめい", "有名", "famous", "na-adjective", "有名な店です。", "Yuumei na mise desu.", "It is a famous shop."),
    w("きらい", "嫌い", "dislike", "na-adjective", "魚が嫌いです。", "Sakana ga kirai desu.", "I dislike fish."),
    w("じょうず", "上手", "skillful", "na-adjective", "料理が上手です。", "Ryouri ga jouzu desu.", "Good at cooking."),
    w("へた", "下手", "unskillful", "na-adjective", "歌が下手です。", "Uta ga heta desu.", "Bad at singing."),
    w("おなじ", "同じ", "same", "na-adjective", "同じ本です。", "Onaji hon desu.", "It is the same book."),
    w("ちがう", "違う", "different, wrong", "verb", "答えが違います。", "Kotae ga chigaimasu.", "The answer is wrong."),
    w("へん", "変", "strange", "na-adjective", "変な音です。", "Hen na oto desu.", "It is a strange sound."),
    w("めずらしい", "珍しい", "rare", "adjective", "珍しい果物です。", "Mezurashii kudamono desu.", "It is a rare fruit."),
    w("ただしい", "正しい", "correct", "adjective", "正しい答えです。", "Tadashii kotae desu.", "It is the correct answer."),
    w("まちがった", "間違った", "wrong (answer)", "adjective", "間違った答えです。", "Machigatta kotae desu.", "It is a wrong answer."),
    w("ふくざつ", "複雑", "complicated", "na-adjective", "問題は複雑です。", "Mondai wa fukuzatsu desu.", "The problem is complicated."),
    w("かんたん", "簡単", "simple, easy", "na-adjective", "この問題は簡単です。", "Kono mondai wa kantan desu.", "This problem is simple."),
    w("たいせつ", "大切", "important", "na-adjective", "大切な人です。", "Taisetsu na hito desu.", "An important person."),
    w("とくべつ", "特別", "special", "na-adjective", "特別な日です。", "Tokubetsu na hi desu.", "It is a special day."),
    w("ふつう", "普通", "normal, ordinary", "na-adjective", "普通の日です。", "Futsuu no hi desu.", "It is an ordinary day."),
    w("いろいろ", "色々", "various", "na-adjective", "色々な本があります。", "Iroiro na hon ga arimasu.", "There are various books."),
    w("ほんとう", "本当", "truth, really", "na-adjective", "本当ですか。", "Hontou desu ka.", "Is it true?"),
    w("うそ", "嘘", "lie", "noun", "嘘をつきません。", "Uso o tsukimasen.", "I do not tell lies."),
    w("あんぜん", "安全", "safe", "na-adjective", "ここは安全です。", "Koko wa anzen desu.", "It is safe here."),
    w("きけん", "危険", "dangerous", "na-adjective", "危険です。", "Kiken desu.", "It is dangerous."),
    # Question words & connectors
    w("なぜ", "何故", "why", "adverb", "何故行きませんか。", "Naze ikimasen ka.", "Why do you not go?"),
    w("どうして", "どうして", "why", "adverb", "どうして来ませんか。", "Doushite kimasen ka.", "Why do you not come?"),
    w("どう", "どう", "how", "adverb", "元気ですか。どうですか。", "Genki desu ka. Dou desu ka.", "How are you?"),
    w("どんな", "どんな", "what kind of", "determiner", "どんな本ですか。", "Donna hon desu ka.", "What kind of book is it?"),
    w("どの", "どの", "which", "determiner", "どの店ですか。", "Dono mise desu ka.", "Which shop is it?"),
    w("いくら", "いくら", "how much", "adverb", "いくらですか。", "Ikura desu ka.", "How much is it?"),
    w("いくつ", "いくつ", "how many", "pronoun", "いくつありますか。", "Ikutsu arimasu ka.", "How many are there?"),
    w("だれの", "誰の", "whose", "pronoun", "これは誰の本ですか。", "Kore wa dare no hon desu ka.", "Whose book is this?"),
    # Food & dining extended
    w("すし", "寿司", "sushi", "noun", "寿司を食べます。", "Sushi o tabemasu.", "I eat sushi."),
    w("さしみ", "刺身", "sashimi", "noun", "刺身が好きです。", "Sashimi ga suki desu.", "I like sashimi."),
    w("てんぷら", "天ぷら", "tempura", "noun", "天ぷらを注文します。", "Tenpura o chuumon shimasu.", "I order tempura."),
    w("うどん", "うどん", "udon noodles", "noun", "うどんを食べます。", "Udon o tabemasu.", "I eat udon."),
    w("そば", "そば", "soba noodles", "noun", "そばが好きです。", "Soba ga suki desu.", "I like soba."),
    w("べんとう", "弁当", "boxed lunch", "noun", "弁当を買います。", "Bentou o kaimasu.", "I buy a boxed lunch."),
    w("みそしる", "味噌汁", "miso soup", "noun", "味噌汁を飲みます。", "Misoshiru o nomimasu.", "I drink miso soup."),
    w("とうふ", "豆腐", "tofu", "noun", "豆腐を食べます。", "Toufu o tabemasu.", "I eat tofu."),
    w("さとう", "砂糖", "sugar", "noun", "砂糖を入れます。", "Satou o iremasu.", "I add sugar."),
    w("しお", "塩", "salt", "noun", "塩を入れます。", "Shio o iremasu.", "I add salt."),
    w("しょうゆ", "醤油", "soy sauce", "noun", "醤油をかけます。", "Shouyu o kakemasu.", "I pour soy sauce."),
    w("おかし", "お菓子", "sweets, snacks", "noun", "お菓子を食べます。", "Okashi o tabemasu.", "I eat sweets."),
    w("レストラン", "", "restaurant", "noun", "レストランで食べます。", "Resutoran de tabemasu.", "I eat at a restaurant."),
    w("メニュー", "", "menu", "noun", "メニューをください。", "Menyuu o kudasai.", "Menu, please."),
    w("ちゅうもん", "注文", "order", "noun", "注文をお願いします。", "Chuumon o onegaishimasu.", "I would like to order."),
    # Katakana / modern life
    w("パソコン", "", "computer", "noun", "パソコンを使います。", "Pasokon o tsukaimasu.", "I use a computer."),
    w("カメラ", "", "camera", "noun", "カメラを持っています。", "Kamera o motte imasu.", "I have a camera."),
    w("チーズ", "", "cheese", "noun", "チーズが好きです。", "Chiizu ga suki desu.", "I like cheese."),
    w("バター", "", "butter", "noun", "バターを塗ります。", "Bataa o nurimasu.", "I spread butter."),
    w("ビール", "", "beer", "noun", "ビールを飲みます。", "Biiru o nomimasu.", "I drink beer."),
    w("タバコ", "", "tobacco, cigarettes", "noun", "タバコは吸いません。", "Tabako wa suimasen.", "I do not smoke."),
    w("エアコン", "", "air conditioner", "noun", "エアコンをつけます。", "Eakon o tsukemasu.", "I turn on the AC."),
    w("エスカレーター", "", "escalator", "noun", "エスカレーターに乗ります。", "Esukareetaa ni norimasu.", "I ride the escalator."),
    w("インターネット", "", "internet", "noun", "インターネットを使います。", "Intaanetto o tsukaimasu.", "I use the internet."),
    w("クレジットカード", "", "credit card", "noun", "クレジットカードで払います。", "Kurejitto kaado de haraimasu.", "I pay by credit card."),
    w("コピー", "", "copy", "noun", "コピーを取ります。", "Kopii o torimasu.", "I make a copy."),
    w("ボールペン", "", "ballpoint pen", "noun", "ボールペンで書きます。", "Boorupen de kakimasu.", "I write with a ballpoint pen."),
    w("はさみ", "はさみ", "scissors", "noun", "はさみを使います。", "Hasami o tsukaimasu.", "I use scissors."),
    w("のり", "糊", "glue", "noun", "糊で貼ります。", "Nori de harimasu.", "I stick it with glue."),
    w("けしゴム", "消しゴム", "eraser", "noun", "消しゴムで消します。", "Keshigomu de keshimasu.", "I erase with an eraser."),
    w("じょうぎ", "定規", "ruler", "noun", "定規を使います。", "Jougi o tsukaimasu.", "I use a ruler."),
    w("かばん", "鞄", "bag", "noun", "鞄に入れます。", "Kaban ni iremasu.", "I put it in the bag."),
    w("かさ", "傘", "umbrella", "noun", "傘を持ちます。", "Kasa o mochimasu.", "I carry an umbrella."),
    w("ハンカチ", "", "handkerchief", "noun", "ハンカチを使います。", "Hankachi o tsukaimasu.", "I use a handkerchief."),
    # Society & events
    w("やくそく", "約束", "promise, appointment", "noun", "約束があります。", "Yakusoku ga arimasu.", "I have an appointment."),
    w("よてい", "予定", "plan, schedule", "noun", "予定を変えます。", "Yotei o kaemasu.", "I change the plan."),
    w("じゅんび", "準備", "preparation", "noun", "準備をします。", "Junbi o shimasu.", "I prepare."),
    w("ようじ", "用事", "errand, business", "noun", "用事があります。", "Youji ga arimasu.", "I have an errand."),
    w("つごう", "都合", "convenience, circumstances", "noun", "都合がいいです。", "Tsugou ga ii desu.", "It is convenient."),
    w("りゆう", "理由", "reason", "noun", "理由を教えてください。", "Riyuu o oshiete kudasai.", "Please tell me the reason."),
    w("けっか", "結果", "result", "noun", "結果を待ちます。", "Kekka o machimasu.", "I wait for the result."),
    w("げんいん", "原因", "cause", "noun", "原因は何ですか。", "Genin wa nan desu ka.", "What is the cause?"),
    w("きそく", "規則", "rule", "noun", "規則を守ります。", "Kisoku o mamorimasu.", "I follow the rules."),
    w("ぜいきん", "税金", "tax", "noun", "税金を払います。", "Zeikin o haraimasu.", "I pay taxes."),
    w("りょうきん", "料金", "fee, charge", "noun", "料金はいくらですか。", "Ryoukin wa ikura desu ka.", "How much is the fee?"),
    w("わりびき", "割引", "discount", "noun", "割引があります。", "Waribiki ga arimasu.", "There is a discount."),
    w("げんきん", "現金", "cash", "noun", "現金で払います。", "Genkin de haraimasu.", "I pay in cash."),
    w("おつり", "お釣り", "change (money)", "noun", "お釣りをください。", "Otsuri o kudasai.", "Change, please."),
    w("しょうひぜい", "消費税", "consumption tax", "noun", "消費税がかかります。", "Shouhizei ga kakarimasu.", "Consumption tax applies."),
    # Time & sequence
    w("さいしょ", "最初", "first, beginning", "noun", "最初は難しいです。", "Saisho wa muzukashii desu.", "At first it is difficult."),
    w("さいご", "最後", "last, end", "noun", "最後まで頑張ります。", "Saigo made ganbarimasu.", "I try until the end."),
    w("つぎ", "次", "next", "noun", "次の駅です。", "Tsugi no eki desu.", "It is the next station."),
    w("まえ", "前", "before, front", "noun", "食事の前に手を洗います。", "Shokuji no mae ni te o araimasu.", "I wash hands before eating."),
    w("あと", "後", "after, later", "noun", "後で電話します。", "Ato de denwa shimasu.", "I will call later."),
    w("べつ", "別", "separate, another", "noun", "別の店へ行きます。", "Betsu no mise e ikimasu.", "I go to another shop."),
    w("はじめ", "初め", "beginning", "noun", "初めまして。", "Hajimemashite.", "Nice to meet you."),
    w("おわり", "終わり", "end", "noun", "終わりです。", "Owari desu.", "It is the end."),
    w("さいきん", "最近", "recently", "noun", "最近忙しいです。", "Saikin isogashii desu.", "I have been busy recently."),
    w("たいへん", "大変", "tough, very", "na-adjective", "大変ですね。", "Taihen desu ne.", "That is tough."),
    # Counters & quantities
    w("ほん", "本", "counter for long objects", "counter", "本を二冊買います。", "Hon o nisatsu kaimasu.", "I buy two books."),
    w("まい", "枚", "counter for flat objects", "counter", "紙を三枚使います。", "Kami o sanmai tsukaimasu.", "I use three sheets."),
    w("にん", "人", "counter for people", "counter", "三人来ました。", "Sannin kimashita.", "Three people came."),
    w("かい", "回", "counter for times", "counter", "二回行きました。", "Nikai ikimashita.", "I went twice."),
    w("ど", "度", "counter for occurrences", "counter", "一度行きました。", "Ichido ikimashita.", "I went once."),
    w("だい", "台", "counter for machines", "counter", "車が一台あります。", "Kuruma ga ichidai arimasu.", "There is one car."),
    w("さつ", "冊", "counter for books", "counter", "本を一冊買います。", "Hon o issatsu kaimasu.", "I buy one book."),
    w("こ", "個", "counter for small objects", "counter", "りんごを三個買います。", "Ringo o sanko kaimasu.", "I buy three apples."),
    w("ふくろ", "袋", "bag, sack", "noun", "袋に入れます。", "Fukuro ni iremasu.", "I put it in a bag."),
    w("びん", "瓶", "bottle", "noun", "瓶を二つ買います。", "Bin o futatsu kaimasu.", "I buy two bottles."),
    # Nature & weather extended
    w("くも", "雲", "cloud", "noun", "雲が多いです。", "Kumo ga ooi desu.", "There are many clouds."),
    w("にじ", "虹", "rainbow", "noun", "虹が見えます。", "Niji ga miemasu.", "I can see a rainbow."),
    w("かみなり", "雷", "thunder", "noun", "雷が鳴ります。", "Kaminari ga narimasu.", "Thunder rumbles."),
    w("きり", "霧", "fog", "noun", "霧が出ています。", "Kiri ga dete imasu.", "There is fog."),
    w("つゆ", "梅雨", "rainy season", "noun", "梅雨の季節です。", "Tsuyu no kisetsu desu.", "It is the rainy season."),
    w("たいふう", "台風", "typhoon", "noun", "台風が来ます。", "Taifuu ga kimasu.", "A typhoon is coming."),
    w("じしん", "地震", "earthquake", "noun", "地震がありました。", "Jishin ga arimashita.", "There was an earthquake."),
    w("かがく", "科学", "science", "noun", "科学が好きです。", "Kagaku ga suki desu.", "I like science."),
    w("れきし", "歴史", "history", "noun", "歴史を勉強します。", "Rekishi o benkyou shimasu.", "I study history."),
    w("ちり", "地理", "geography", "noun", "地理の授業です。", "Chiri no jugyou desu.", "It is geography class."),
    # Post & communication
    w("ふうとう", "封筒", "envelope", "noun", "封筒に入れます。", "Fuutou ni iremasu.", "I put it in an envelope."),
    w("きって", "切手", "postage stamp", "noun", "切手を買います。", "Kitte o kaimasu.", "I buy stamps."),
    w("はがき", "葉書", "postcard", "noun", "葉書を送ります。", "Hagaki o okurimasu.", "I send a postcard."),
    w("しょうたい", "招待", "invitation", "noun", "招待状をもらいました。", "Shoutaijou o moraimashita.", "I received an invitation."),
    w("おしらせ", "お知らせ", "notice, announcement", "noun", "お知らせを読みます。", "Oshirase o yomimasu.", "I read the notice."),
    w("ニュース", "", "news", "noun", "ニュースを見ます。", "Nyuusu o mimasu.", "I watch the news."),
    w("ラジオ", "", "radio", "noun", "ラジオを聞きます。", "Rajio o kikimasu.", "I listen to the radio."),
    w("テレビ", "", "television", "noun", "テレビを見ます。", "Terebi o mimasu.", "I watch TV."),
    w("でんき", "電気", "electricity", "noun", "電気がついています。", "Denki ga tsuite imasu.", "The light is on."),
    w("でんとう", "電灯", "electric light", "noun", "電灯を消します。", "Dentou o keshimasu.", "I turn off the light."),
    # More verbs & expressions
    w("つとめる", "勤める", "to work for", "verb", "会社に勤めています。", "Kaisha ni tsutomete imasu.", "I work for a company."),
    w("やめる", "辞める", "to quit", "verb", "仕事を辞めます。", "Shigoto o yamemasu.", "I quit my job."),
    w("うける", "受ける", "to take (exam)", "verb", "試験を受けます。", "Shiken o ukemasu.", "I take an exam."),
    w("おしえる", "教える", "to teach", "verb", "日本語を教えます。", "Nihongo o oshiemasu.", "I teach Japanese."),
    w("ならう", "習う", "to learn", "verb", "ピアノを習います。", "Piano o naraimasu.", "I learn piano."),
    w("おぼえる", "覚える", "to memorize", "verb", "漢字を覚えます。", "Kanji o oboemasu.", "I memorize kanji."),
    w("わすれる", "忘れる", "to forget", "verb", "名前を忘れました。", "Namae o wasuremashita.", "I forgot the name."),
    w("おもいだす", "思い出す", "to remember, recall", "verb", "思い出しました。", "Omoidashimashita.", "I remembered."),
    w("かんがえる", "考える", "to think", "verb", "よく考えます。", "Yoku kangaemasu.", "I think carefully."),
    w("しんぱいする", "心配する", "to worry", "verb", "心配しないでください。", "Shinpai shinaide kudasai.", "Please do not worry."),
    w("たのしむ", "楽しむ", "to enjoy", "verb", "旅行を楽しみます。", "Ryokou o tanoshimimasu.", "I enjoy the trip."),
    w("びっくりする", "びっくりする", "to be surprised", "verb", "びっくりしました。", "Bikkuri shimashita.", "I was surprised."),
    w("うれしがる", "嬉しがる", "to be glad", "verb", "嬉しがっています。", "Ureshigatte imasu.", "They are glad."),
    w("かなしむ", "悲しむ", "to grieve", "verb", "悲しんでいます。", "Kanashinde imasu.", "They are grieving."),
    w("おこる", "怒る", "to get angry", "verb", "怒らないでください。", "Okoranaide kudasai.", "Please do not get angry."),
    # Additional high-frequency N5
    w("りんご", "林檎", "apple", "noun", "林檎を食べます。", "Ringo o tabemasu.", "I eat an apple."),
    w("みかん", "蜜柑", "mandarin orange", "noun", "蜜柑が好きです。", "Mikan ga suki desu.", "I like mandarins."),
    w("ぶどう", "葡萄", "grape", "noun", "葡萄を買います。", "Budou o kaimasu.", "I buy grapes."),
    w("いちご", "苺", "strawberry", "noun", "苺が甘いです。", "Ichigo ga amai desu.", "Strawberries are sweet."),
    w("すいか", "西瓜", "watermelon", "noun", "西瓜を食べます。", "Suika o tabemasu.", "I eat watermelon."),
    w("とうもろこし", "玉蜀黍", "corn", "noun", "玉蜀黍が好きです。", "Toumorokoshi ga suki desu.", "I like corn."),
    w("じゃがいも", "じゃが芋", "potato", "noun", "じゃが芋を買います。", "Jagaimo o kaimasu.", "I buy potatoes."),
    w("たまねぎ", "玉葱", "onion", "noun", "玉葱を切ります。", "Tamanegi o kirimasu.", "I cut the onion."),
    w("にんじん", "人参", "carrot", "noun", "人参を食べます。", "Ninjin o tabemasu.", "I eat carrots."),
    w("きゅうり", "胡瓜", "cucumber", "noun", "胡瓜を切ります。", "Kyuuri o kirimasu.", "I slice cucumber."),
    w("なす", "茄子", "eggplant", "noun", "茄子を食べます。", "Nasu o tabemasu.", "I eat eggplant."),
    w("きのこ", "茸", "mushroom", "noun", "茸を料理します。", "Kinoko o ryouri shimasu.", "I cook mushrooms."),
    w("えび", "海老", "shrimp", "noun", "海老を食べます。", "Ebi o tabemasu.", "I eat shrimp."),
    w("かに", "蟹", "crab", "noun", "蟹が好きです。", "Kani ga suki desu.", "I like crab."),
    w("たこ", "蛸", "octopus", "noun", "蛸を食べます。", "Tako o tabemasu.", "I eat octopus."),
    w("いか", "烏賊", "squid", "noun", "烏賊を食べます。", "Ika o tabemasu.", "I eat squid."),
    w("ぶたにく", "豚肉", "pork", "noun", "豚肉を買います。", "Butaniku o kaimasu.", "I buy pork."),
    w("ぎゅうにく", "牛肉", "beef", "noun", "牛肉を食べます。", "Gyuuniku o tabemasu.", "I eat beef."),
    w("とりにく", "鶏肉", "chicken meat", "noun", "鶏肉を料理します。", "Toriniku o ryouri shimasu.", "I cook chicken."),
    w("ソーセージ", "", "sausage", "noun", "ソーセージを食べます。", "Sooseji o tabemasu.", "I eat sausage."),
    # Stationery & classroom extras
    w("ノート", "", "notebook", "noun", "ノートに書きます。", "Nooto ni kakimasu.", "I write in the notebook."),
    w("てちょう", "手帳", "planner, notebook", "noun", "手帳を持っています。", "Techou o motte imasu.", "I have a planner."),
    w("かみ", "紙", "paper", "noun", "紙をください。", "Kami o kudasai.", "Paper, please."),
    w("えんぴつ", "鉛筆", "pencil", "noun", "鉛筆で書きます。", "Enpitsu de kakimasu.", "I write with a pencil."),
    w("いろえんぴつ", "色鉛筆", "colored pencil", "noun", "色鉛筆で描きます。", "Iroenpitsu de kakimasu.", "I draw with colored pencils."),
    w("けいさんき", "計算機", "calculator", "noun", "計算機を使います。", "Keisanki o tsukaimasu.", "I use a calculator."),
    w("ちず", "地図", "map", "noun", "地図を見ます。", "Chizu o mimasu.", "I look at the map."),
    w("じしょ", "辞書", "dictionary", "noun", "辞書を使います。", "Jisho o tsukaimasu.", "I use a dictionary."),
    w("え", "絵", "picture", "noun", "絵を描きます。", "E o kakimasu.", "I draw a picture."),
    w("しゃしん", "写真", "photograph", "noun", "写真を撮ります。", "Shashin o torimasu.", "I take a photo."),
    # Final gap-fill batch
    w("ひるま", "昼間", "daytime", "noun", "昼間は暖かいです。", "Hiruma wa atatakai desu.", "It is warm during the day."),
    w("よなか", "夜中", "middle of the night", "noun", "夜中に起きました。", "Yonaka ni okimashita.", "I woke up in the middle of the night."),
    w("しょうがっこう", "小学校", "elementary school", "noun", "小学校へ行きます。", "Shougakkou e ikimasu.", "I go to elementary school."),
    w("ちゅうがっこう", "中学校", "middle school", "noun", "中学校の前です。", "Chuugakkou no mae desu.", "It is in front of middle school."),
    w("こうこう", "高校", "high school", "noun", "高校を卒業しました。", "Koukou o sotsugyou shimashita.", "I graduated high school."),
    w("だいがく", "大学", "university", "noun", "大学へ通います。", "Daigaku e kayotte imasu.", "I attend university."),
    w("そつぎょう", "卒業", "graduation", "noun", "卒業おめでとう。", "Sotsugyou omedetou.", "Congratulations on graduation."),
    w("にゅうがく", "入学", "enrollment", "noun", "入学しました。", "Nyuugaku shimashita.", "I enrolled."),
    w("しごとば", "仕事場", "workplace", "noun", "仕事場へ行きます。", "Shigotoba e ikimasu.", "I go to the workplace."),
    w("かいぎしつ", "会議室", "meeting room", "noun", "会議室で待ちます。", "Kaigishitsu de machimasu.", "I wait in the meeting room."),
    w("うけつけ", "受付", "reception", "noun", "受付で聞きます。", "Uketsuke de kikimasu.", "I ask at reception."),
    w("まどぐち", "窓口", "counter window", "noun", "窓口へ行きます。", "Madoguchi e ikimasu.", "I go to the counter."),
    w("しょくどう", "食堂", "cafeteria", "noun", "食堂で食べます。", "Shokudou de tabemasu.", "I eat in the cafeteria."),
    w("たいいくかん", "体育館", "gymnasium", "noun", "体育館で運動します。", "Taiikukan de undou shimasu.", "I exercise in the gym."),
    w("プール", "", "swimming pool", "noun", "プールで泳ぎます。", "Puuru de oyogimasu.", "I swim in the pool."),
    w("こうえん", "公園", "park", "noun", "公園で遊びます。", "Kouen de asobimasu.", "I play in the park."),
    w("どうぶつえん", "動物園", "zoo", "noun", "動物園へ行きます。", "Doubutsuen e ikimasu.", "I go to the zoo."),
    w("すいぞくかん", "水族館", "aquarium", "noun", "水族館を見学します。", "Suizokukan o kengaku shimasu.", "I visit the aquarium."),
    w("おてら", "お寺", "temple", "noun", "お寺を見ます。", "Otera o mimasu.", "I see a temple."),
    w("じんじゃ", "神社", "shrine", "noun", "神社へ行きます。", "Jinja e ikimasu.", "I go to a shrine."),
    # Wave 8 gap-fill — final N5 coverage
    w("やく", "焼く", "to bake, grill", "verb", "魚を焼きます。", "Sakana o yakimasu.", "I grill fish."),
    w("にる", "煮る", "to boil, simmer", "verb", "野菜を煮ます。", "Yasai o nimasu.", "I boil vegetables."),
    w("およぐ", "泳ぐ", "to swim", "verb", "海で泳ぎます。", "Umi de oyogimasu.", "I swim in the sea."),
    w("おどる", "踊る", "to dance", "verb", "ダンスを踊ります。", "Dansu o odorimasu.", "I dance."),
    w("うたう", "歌う", "to sing", "verb", "歌を歌います。", "Uta o utaimasu.", "I sing a song."),
    w("わらう", "笑う", "to laugh", "verb", "笑います。", "Waraimasu.", "I laugh."),
    w("なく", "泣く", "to cry", "verb", "泣きました。", "Nakimashita.", "I cried."),
    w("こまる", "困る", "to be troubled", "verb", "困っています。", "Komatte imasu.", "I am troubled."),
    w("よろこぶ", "喜ぶ", "to rejoice", "verb", "喜んでいます。", "Yorokonde imasu.", "I am delighted."),
    w("かつ", "勝つ", "to win", "verb", "試合に勝ちます。", "Shiai ni kachimasu.", "I win the match."),
    w("まける", "負ける", "to lose", "verb", "試合に負けました。", "Shiai ni makemashita.", "I lost the match."),
    w("うごく", "動く", "to move", "verb", "車が動きます。", "Kuruma ga ugokimasu.", "The car moves."),
    w("まわる", "回る", "to turn, rotate", "verb", "地球は回ります。", "Chikyuu wa mawarimasu.", "The Earth rotates."),
    w("わたる", "渡る", "to cross", "verb", "道を渡ります。", "Michi o watarimasu.", "I cross the road."),
    w("たてる", "建てる", "to build", "verb", "家を建てます。", "Ie o tatemasu.", "I build a house."),
    w("こわす", "壊す", "to break (something)", "verb", "おもちゃを壊しました。", "Omocha o kowashimashita.", "I broke the toy."),
    w("なおる", "直る", "to be fixed", "verb", "時計が直りました。", "Tokei ga naorimashita.", "The watch was fixed."),
    w("つける", "付ける", "to attach, turn on", "verb", "名前を付けます。", "Namae o tsukemasu.", "I attach a name."),
    w("はずす", "外す", "to remove", "verb", "帽子を外します。", "Boushi o hazushimasu.", "I remove my hat."),
    w("つたえる", "伝える", "to convey", "verb", "メッセージを伝えます。", "Messeji o tsutaemasu.", "I convey the message."),
    w("せつめいする", "説明する", "to explain", "verb", "説明します。", "Setsumei shimasu.", "I explain."),
    w("しょうかいする", "紹介する", "to introduce", "verb", "友達を紹介します。", "Tomodachi o shoukai shimasu.", "I introduce a friend."),
    w("れんらくする", "連絡する", "to contact", "verb", "連絡します。", "Renraku shimasu.", "I will contact you."),
    w("かんじる", "感じる", "to feel", "verb", "寒さを感じます。", "Samusa o kanjimasu.", "I feel the cold."),
    w("しらせる", "知らせる", "to notify", "verb", "知らせます。", "Shiraseru.", "I will notify you."),
    w("はじまる", "始まる", "to begin (intransitive)", "verb", "会議が始まります。", "Kaigi ga hajimarimasu.", "The meeting begins."),
    w("あく", "開く", "to open", "verb", "ドアが開きます。", "Doa ga akimasu.", "The door opens."),
    w("しめる", "閉じる", "to close", "verb", "窓を閉じます。", "Mado o tojimasu.", "I close the window."),
    w("つく", "付く", "to be attached, turn on", "verb", "電気が付きます。", "Denki ga tsukimasu.", "The light turns on."),
    w("きえる", "消える", "to disappear, go out", "verb", "電気が消えます。", "Denki ga kierimasu.", "The light goes out."),
    w("ひかる", "光る", "to shine", "verb", "星が光ります。", "Hoshi ga hikarimasu.", "Stars shine."),
    w("おと", "音", "sound", "noun", "音が聞こえます。", "Oto ga kikoemasu.", "I hear a sound."),
    w("こえ", "声", "voice", "noun", "声が大きいです。", "Koe ga ookii desu.", "The voice is loud."),
    w("あじ", "味", "taste, flavor", "noun", "味がいいです。", "Aji ga ii desu.", "It tastes good."),
    w("におい", "匂い", "smell, odor", "noun", "いい匂いです。", "Ii nioi desu.", "It smells good."),
    w("しなもの", "品物", "goods, article", "noun", "品物を見ます。", "Shinamono o mimasu.", "I look at the goods."),
    w("しょうひん", "商品", "product, merchandise", "noun", "商品を買います。", "Shouhin o kaimasu.", "I buy the product."),
    w("ざいりょう", "材料", "ingredients, materials", "noun", "材料を買います。", "Zairyou o kaimasu.", "I buy ingredients."),
    w("けしき", "景色", "scenery", "noun", "景色がきれいです。", "Keshiki ga kirei desu.", "The scenery is beautiful."),
    w("まつり", "祭り", "festival", "noun", "祭りに行きます。", "Matsuri ni ikimasu.", "I go to the festival."),
    w("きゅうじつ", "休日", "holiday, day off", "noun", "休日は休みます。", "Kyuujitsu wa yasumimasu.", "I rest on holidays."),
    w("しゅくじつ", "祝日", "national holiday", "noun", "祝日です。", "Shukujitsu desu.", "It is a national holiday."),
    w("なつやすみ", "夏休み", "summer vacation", "noun", "夏休みに旅行します。", "Natsuyasumi ni ryokou shimasu.", "I travel during summer break."),
    w("ふゆやすみ", "冬休み", "winter vacation", "noun", "冬休みは長いです。", "Fuyuyasumi wa nagai desu.", "Winter break is long."),
    w("れんきゅう", "連休", "consecutive holidays", "noun", "連休を楽しみます。", "Renkyuu o tanoshimi masu.", "I enjoy the long weekend."),
    w("でんとうぶんか", "伝統文化", "traditional culture", "noun", "伝統文化を学びます。", "Dentou bunka o manabimasu.", "I learn traditional culture."),
    w("しゅうかん", "習慣", "habit, custom", "noun", "いい習慣です。", "Ii shuukan desu.", "It is a good habit."),
    w("かんけい", "関係", "relationship, connection", "noun", "関係があります。", "Kankei ga arimasu.", "There is a connection."),
    w("しゃかい", "社会", "society", "noun", "社会を勉強します。", "Shakai o benkyou shimasu.", "I study society."),
    w("へいわ", "平和", "peace", "noun", "平和が大切です。", "Heiwa ga taisetsu desu.", "Peace is important."),
    w("せかいじゅう", "世界中", "all over the world", "noun", "世界中を旅行します。", "Sekaijuu o ryokou shimasu.", "I travel around the world."),
    w("にほんご", "日本語", "Japanese language", "noun", "日本語を勉強します。", "Nihongo o benkyou shimasu.", "I study Japanese."),
    w("えいご", "英語", "English language", "noun", "英語が話せます。", "Eigo ga hanasemasu.", "I can speak English."),
    w("がいこくご", "外国語", "foreign language", "noun", "外国語を習います。", "Gaikokugo o naraimasu.", "I learn a foreign language."),
    w("はなし", "話", "talk, story", "noun", "話を聞きます。", "Hanashi o kikimasu.", "I listen to the story."),
    w("はなしあい", "話し合い", "discussion", "noun", "話し合いをします。", "Hanashiai o shimasu.", "We have a discussion."),
    w("そうだん", "相談", "consultation", "noun", "相談があります。", "Soudan ga arimasu.", "I have a consultation."),
    w("れい", "例", "example", "noun", "例を見せてください。", "Rei o misete kudasai.", "Please show an example."),
    w("ほうほう", "方法", "method, way", "noun", "方法を教えてください。", "Houhou o oshiete kudasai.", "Please teach me the method."),
    w("じょうきょう", "状況", "situation", "noun", "状況を説明します。", "Joukyou o setsumei shimasu.", "I explain the situation."),
    w("じっさい", "実際", "actually, in fact", "noun", "実際は違います。", "Jissai wa chigaimasu.", "Actually it is different."),
    w("いっしょうけんめい", "一生懸命", "with all one's effort", "adverb", "一生懸命勉強します。", "Isshoukenmei benkyou shimasu.", "I study hard."),
    w("ぜったい", "絶対", "absolutely", "adverb", "絶対行きます。", "Zettai ikimasu.", "I will absolutely go."),
    w("きっと", "きっと", "surely", "adverb", "きっと大丈夫です。", "Kitto daijoubu desu.", "Surely it will be fine."),
    w("たぶん", "多分", "probably", "adverb", "多分雨です。", "Tabun ame desu.", "It will probably rain."),
    w("もちろん", "勿論", "of course", "adverb", "勿論行きます。", "Mochiron ikimasu.", "Of course I will go."),
    w("ぜひ", "是非", "by all means", "adverb", "是非来てください。", "Zehi kite kudasai.", "Please come by all means."),
    w("いっぱい", "一杯", "full, a lot", "adverb", "人が一杯います。", "Hito ga ippai imasu.", "It is full of people."),
    w("すっかり", "すっかり", "completely", "adverb", "すっかり忘れました。", "Sukkari wasuremashita.", "I completely forgot."),
    w("だんだん", "段々", "gradually", "adverb", "段々分かります。", "Dandan wakarimasu.", "I gradually understand."),
    w("どんどん", "どんどん", "rapidly, more and more", "adverb", "どんどん上手になります。", "Dondon jouzu ni narimasu.", "I get better rapidly."),
    w("ぴったり", "ぴったり", "exactly, perfectly", "adverb", "ぴったり合います。", "Pittari aimasu.", "It fits perfectly."),
    w("しっかり", "しっかり", "firmly, properly", "adverb", "しっかり勉強します。", "Shikkari benkyou shimasu.", "I study properly."),
    w("ちゃんと", "ちゃんと", "properly", "adverb", "ちゃんと食べます。", "Chanto tabemasu.", "I eat properly."),
    w("すぐに", "直ぐに", "immediately", "adverb", "直ぐに行きます。", "Sugu ni ikimasu.", "I go immediately."),
    w("ゆっくりと", "ゆっくりと", "slowly", "adverb", "ゆっくりと歩きます。", "Yukkuri to arukimasu.", "I walk slowly."),
    w("はっきり", "はっきり", "clearly", "adverb", "はっきり言います。", "Hakkiri iimasu.", "I say it clearly."),
    w("じゅうぶん", "十分", "enough", "na-adjective", "十分です。", "Juubun desu.", "It is enough."),
    w("ひつよう", "必要", "necessary", "na-adjective", "必要があります。", "Hitsuyou ga arimasu.", "It is necessary."),
    w("だめ", "駄目", "no good, not allowed", "na-adjective", "駄目です。", "Dame desu.", "It is not allowed."),
    w("だいじょうぶ", "大丈夫", "okay, all right", "na-adjective", "大丈夫ですか。", "Daijoubu desu ka.", "Are you okay?"),
    w("にがて", "苦手", "weak at, not good at", "na-adjective", "数学が苦手です。", "Suugaku ga nigate desu.", "I am weak at math."),
    w("とくい", "得意", "good at, strong point", "na-adjective", "料理が得意です。", "Ryouri ga tokui desu.", "I am good at cooking."),
    w("にんき", "人気", "popular", "na-adjective", "人気があります。", "Ninki ga arimasu.", "It is popular."),
    w("しんせつ", "親切", "kind", "na-adjective", "親切な人です。", "Shinsetsu na hito desu.", "A kind person."),
    w("りょうしん", "両親", "parents", "noun", "両親に会います。", "Ryoushin ni aimasu.", "I meet my parents."),
    w("しつれい", "失礼", "excuse me, rude", "na-adjective", "失礼しました。", "Shitsurei shimashita.", "Excuse me."),
    w("おじゃま", "お邪魔", "intrusion", "noun", "お邪魔します。", "Ojama shimasu.", "Sorry to intrude."),
    w("さくぶん", "作文", "essay, composition", "noun", "作文を書きます。", "Sakubun o kakimasu.", "I write an essay."),
    w("ひょうげん", "表現", "expression", "noun", "表現を練習します。", "Hyougen o renshuu shimasu.", "I practice expressions."),
    w("れいぶん", "例文", "example sentence", "noun", "例文を読みます。", "Reibun o yomimasu.", "I read example sentences."),
    w("たんご", "単語", "vocabulary word", "noun", "単語を覚えます。", "Tango o oboemasu.", "I memorize vocabulary."),
    w("ぶんぽう", "文法", "grammar", "noun", "文法を勉強します。", "Bunpou o benkyou shimasu.", "I study grammar."),
    w("まぜる", "混ぜる", "to mix", "verb", "材料を混ぜます。", "Zairyou o mazemasu.", "I mix the ingredients."),
    w("こねる", "捏ねる", "to knead", "verb", "パンを捏ねます。", "Pan o konemasu.", "I knead bread dough."),
    w("すく", "掬う", "to scoop", "verb", "スープを掬います。", "Suupu o sukumasu.", "I scoop soup."),
    w("すくう", "救う", "to rescue", "verb", "人を救います。", "Hito o sukuimasu.", "I rescue a person."),
    w("さがす", "探す", "to search for", "verb", "仕事を探します。", "Shigoto o sagashimasu.", "I search for a job."),
    w("みつかる", "見つかる", "to be found", "verb", "仕事が見つかりました。", "Shigoto ga mitsukarimashita.", "I found a job."),
    w("とどく", "届く", "to reach, arrive", "verb", "手紙が届きます。", "Tegami ga todokimasu.", "The letter arrives."),
    w("ふえる", "増える", "to increase", "verb", "友達が増えます。", "Tomodachi ga fuemasu.", "Friends increase."),
    w("へる", "減る", "to decrease", "verb", "体重が減ります。", "Taijuu ga herimasu.", "My weight decreases."),
    w("かわる", "変わる", "to change", "verb", "季節が変わります。", "Kisetsu ga kawarimasu.", "The season changes."),
    w("とりかえる", "取り替える", "to replace", "verb", "電球を取り替えます。", "Denkyuu o torikaemasu.", "I replace the light bulb."),
    w("そだてる", "育てる", "to raise, grow", "verb", "花を育てます。", "Hana o sodatemasu.", "I grow flowers."),
    w("そだつ", "育つ", "to grow up", "verb", "子供が育ちます。", "Kodomo ga sodachimasu.", "Children grow up."),
]

BANK: list[Word] = weekdays() + months() + CURATED
