/** Story / dialogue slugs → vocabulary kana keys for comprehension SRS. */
export const COMPREHENSION_VOCAB_BY_STORY_SLUG: Record<string, string[]> = {
  "tanaka-morning": ["あさ", "ごはん"],
  "first-day-school": ["がっこう", "ともだち"],
  "weekend-plans": ["しゅうまつ", "いく"],
  "rainy-day": ["あめ", "いえ"],
  "at-the-market": ["みせ", "やさい"],
  "train-commute": ["でんしゃ", "えき"],
  "birthday-surprise": ["たんじょうび", "プレゼント"],
  "weekend-trip": ["りょこう", "みず"],
  "summer-festival": ["まつり", "たのしい"],
  "first-part-time-job": ["しごと", "アルバイト"],
  "cafe-order": ["コーヒー", "ください"],
  "meeting-friend": ["ともだち", "あう"],
  "at-the-doctor": ["びょういん", "いたい"],
  "buying-clothes": ["ふく", "かう"],
  "making-plans": ["よてい", "あう"],
  "at-the-hotel": ["ホテル", "へや"],
  "asking-help": ["たすけ", "ください"],
  "at-the-post-office": ["ゆうびん", "おく"],
  "bus-schedule": ["バス", "じかん"],
  "ordering-taxi": ["タクシー", "よぶ"],
};

export const COMPREHENSION_VOCAB_BY_LISTENING_SLUG: Record<string, string[]> = {
  "greeting-friend": ["こんにちは", "げんき"],
  "self-introduction": ["はじめまして", "なまえ"],
  "at-the-shop": ["みせ", "いくら"],
  "finding-station": ["えき", "どこ"],
  "ordering-food": ["たべる", "ください"],
  "asking-time": ["じかん", "なんじ"],
  "weather-today": ["てんき", "あめ"],
  "at-restaurant": ["レストラン", "ちゅうもん"],
  "making-appointment": ["よやく", "あう"],
  "asking-directions-left": ["みぎ", "ひだり"],
  "buying-ticket": ["きっぷ", "かう"],
  "phone-message": ["でんわ", "メッセージ"],
  "feeling-sick": ["びょうき", "だいじょうぶ"],
  "classroom-question": ["しつもん", "せんせい"],
  "weekend-hobby": ["しゅうまつ", "しゅみ"],
  "hotel-checkin": ["チェックイン", "へや"],
  "asking-price-discount": ["ねだん", "やすい"],
  "meeting-friend-station": ["えき", "まつ"],
  "describing-room": ["へや", "ひろい"],
  "birthday-party": ["たんじょうび", "パーティー"],
  "lost-item": ["わすれる", "もの"],
  "taking-photo": ["しゃしん", "とる"],
  "study-plan": ["べんきょう", "よてい"],
  "goodbye-friend": ["さようなら", "また"],
  "weather-forecast": ["てんき", "はれ"],
  "asking-restroom": ["トイレ", "どこ"],
  "library-hours": ["としょかん", "じかん"],
  "inviting-lunch": ["ひるごはん", "いっしょ"],
  "missed-train": ["でんしゃ", "おくれる"],
  "thanking-help": ["ありがとう", "たすけ"],
  "daily-conversations": ["かいわ", "れんしゅう"],
  "greeting-at-station": ["えき", "こんにちは"],
  "shop-conversation": ["みせ", "かう"],
};
