import type {
  YamaAssetEntry,
  YamaAssetPack,
  YamaAssetTheme,
  YamaExpression,
  YamaExpressionPackId,
} from "@/features/yama/types/yama.types";

const APPROVED_PUBLIC_PATHS: Record<string, string> = {
  yama_main_light_v1: "/mascots/yama_main_light_v1.webp",
  yama_main_dark_v1: "/mascots/yama_main_dark_v1.webp",
  yama_happy_light_v1: "/mascots/yama_happy_light_v1.webp",
  yama_happy_dark_v2: "/mascots/yama_happy_dark_v2.webp",
  yama_celebrating_light_v1: "/mascots/yama_celebrating_light_v1.webp",
  yama_celebrating_dark_v2: "/mascots/yama_celebrating_dark_v2.webp",
  yama_encouraging_light_v1: "/mascots/yama_encouraging_light_v1.webp",
  yama_encouraging_dark_v2: "/mascots/yama_encouraging_dark_v2.webp",
  yama_thinking_light_v1: "/mascots/yama_thinking_light_v1.webp",
  yama_thinking_dark_v2: "/mascots/yama_thinking_dark_v2.webp",
  yama_loading_light_v1: "/mascots/yama_loading_light_v1.webp",
  yama_loading_dark_v2: "/mascots/yama_loading_dark_v2.webp",
  yama_victorious_light_v1: "/mascots/yama_victorious_light_v1.webp",
  yama_victorious_dark_v1: "/mascots/yama_victorious_dark_v1.webp",
  yama_confused_light_v1: "/mascots/yama_confused_light_v1.webp",
  yama_confused_dark_v1: "/mascots/yama_confused_dark_v1.webp",
  yama_teaching_pointing_board_dark_v1:
    "/mascots/yama_teaching_pointing_board_dark_v1.webp",
  yama_teaching_pointing_board_light_v1:
    "/mascots/yama_teaching_pointing_board_light_v1.webp",
  yama_surprised_wide_eyes_dark_v1: "/mascots/yama_surprised_wide_eyes_dark_v1.webp",
  yama_surprised_wide_eyes_light_v1: "/mascots/yama_surprised_wide_eyes_light_v1.webp",
  yama_concerned_supportive_concern_dark_v1:
    "/mascots/yama_concerned_supportive_concern_dark_v1.webp",
  yama_concerned_supportive_concern_light_v1:
    "/mascots/yama_concerned_supportive_concern_light_v1.webp",
  yama_determined_ready_stance_dark_v1:
    "/mascots/yama_determined_ready_stance_dark_v1.webp",
  yama_determined_ready_stance_light_v1:
    "/mascots/yama_determined_ready_stance_light_v1.webp",
  yama_sleeping_resting_dark_v1: "/mascots/yama_sleeping_resting_dark_v1.webp",
  yama_sleeping_resting_light_v1: "/mascots/yama_sleeping_resting_light_v1.webp",
  yama_sad_supportive_disappointed_dark_v1:
    "/mascots/yama_sad_supportive_disappointed_dark_v1.webp",
  yama_sad_supportive_disappointed_light_v1:
    "/mascots/yama_sad_supportive_disappointed_light_v1.webp",
  yama_adventure_hiking_dark_v1: "/mascots/yama_adventure_hiking_dark_v1.webp",
  yama_adventure_hiking_light_v1: "/mascots/yama_adventure_hiking_light_v1.webp",
  yama_training_demo_stance_dark_v1: "/mascots/yama_training_demo_stance_dark_v1.webp",
  yama_training_demo_stance_light_v1:
    "/mascots/yama_training_demo_stance_light_v1.webp",
  yama_seasonal_cherry_blossom_dark_v1:
    "/mascots/yama_seasonal_cherry_blossom_dark_v1.webp",
  yama_seasonal_cherry_blossom_light_v1:
    "/mascots/yama_seasonal_cherry_blossom_light_v1.webp",
  yama_reward_presenting_badge_dark_v1:
    "/mascots/yama_reward_presenting_badge_dark_v1.webp",
  yama_reward_presenting_badge_light_v1:
    "/mascots/yama_reward_presenting_badge_light_v1.webp",
};

const THEMES: readonly YamaAssetTheme[] = ["light", "dark"];

function buildAssetId(
  packId: YamaExpressionPackId,
  variant: string,
  theme: YamaAssetTheme,
  version: number,
): string {
  return `yama_${packId}_${variant}_${theme}_v${version}`;
}

function buildPlannedPackAssets(
  packId: YamaExpressionPackId,
  variants: readonly string[],
  fallbackExpression?: YamaExpression,
): YamaAssetEntry[] {
  return variants.flatMap((variant) =>
    THEMES.map((theme) => {
      const id = buildAssetId(packId, variant, theme, 1);

      return {
        id,
        packId,
        variant,
        theme,
        version: 1,
        status: "planned",
        fallbackExpression,
      } satisfies YamaAssetEntry;
    }),
  );
}

const HAPPY_VARIANTS = [
  "small_smile",
  "big_smile",
  "laughing",
  "proud_smile",
  "excited_smile",
  "cheerful_wave",
  "content_nod",
  "bright_eyes",
  "gentle_grin",
  "sparkle_smile",
] as const;

const CELEBRATING_VARIANTS = [
  "jumping",
  "confetti",
  "victory_pose",
  "fist_pump",
  "cheer_pose",
  "summit_leap",
  "badge_raise",
  "trail_flag",
  "confetti_burst",
  "victory_dance",
  "high_five",
  "star_spin",
  "banner_wave",
  "summit_salute",
  "celebration_spin",
] as const;

const ENCOURAGING_VARIANTS = [
  "gentle_smile",
  "offering_hand",
  "pointing_forward",
  "motivational_stance",
  "steady_nod",
  "open_palm",
  "trail_guide",
  "supportive_wave",
  "ready_climb",
  "pat_on_back",
] as const;

const THINKING_VARIANTS = [
  "hand_on_chin",
  "looking_up",
  "studying_scroll",
  "holding_notebook",
  "reading_notes",
  "pondering",
  "examining_map",
  "crossed_arms_think",
  "scroll_compare",
  "note_review",
  "pattern_study",
  "hint_gesture",
  "focused_read",
  "idea_spark",
  "study_lamp",
] as const;

const TEACHING_VARIANTS = [
  "pointing_board",
  "holding_flashcard",
  "presenting_info",
  "explaining_gesture",
  "lesson_intro",
  "step_demo",
  "example_point",
  "board_write",
  "card_flip",
  "concept_map",
  "tutorial_wave",
  "checkpoint_brief",
  "lesson_overview",
  "demonstration",
  "guided_step",
] as const;

const SURPRISED_VARIANTS = [
  "shocked",
  "amazed",
  "wide_eyes",
  "jaw_drop",
  "double_take",
  "sparkle_surprise",
  "unexpected_find",
  "rare_moment",
  "delighted_shock",
  "wonder_gaze",
] as const;

const CONCERNED_VARIANTS = [
  "worried",
  "sympathetic",
  "concerned_look",
  "supportive_concern",
  "gentle_worry",
  "checking_in",
  "soft_frown",
  "caring_nod",
  "patient_wait",
  "ready_when_you_are",
] as const;

const DETERMINED_VARIANTS = [
  "serious_face",
  "ready_stance",
  "focused_expression",
  "battle_prep",
  "exam_focus",
  "trial_ready",
  "boss_stance",
  "summit_resolve",
  "challenge_accept",
  "sharp_gaze",
  "training_intensity",
  "guardian_face",
  "trial_salute",
  "focus_breath",
  "challenge_ready",
] as const;

const SLEEPING_VARIANTS = [
  "sleeping",
  "yawning",
  "resting",
  "dreaming",
  "dozing",
  "camp_nap",
  "night_rest",
  "soft_snooze",
  "pillow_rest",
  "moonlit_sleep",
] as const;

const CONFUSED_VARIANTS = [
  "tilted_head",
  "scratching_head",
  "questioning",
  "puzzled_brow",
  "unsure_shrug",
  "thinking_tilt",
  "hmm_gesture",
  "lost_map",
  "retry_prompt",
  "gentle_confusion",
] as const;

const SAD_VARIANTS = [
  "disappointed_supportive",
  "sympathetic_sigh",
  "soft_sadness",
  "encouraging_after_loss",
  "streak_sympathy",
  "challenge_miss",
  "gentle_downcast",
  "supportive_frown",
  "we_will_retry",
  "tomorrow_climb",
] as const;

const ADVENTURE_VARIANTS = [
  "walking",
  "hiking",
  "climbing",
  "crossing_bridge",
  "exploring_shrine",
  "binoculars",
  "backpack",
  "trail_scout",
  "map_check",
  "foothills_path",
  "forest_trail",
  "summit_approach",
  "campfire_rest",
  "river_crossing",
  "village_visit",
  "lantern_night",
  "summit_flag",
  "windy_ridge",
  "mist_trail",
  "stone_steps",
  "rope_bridge",
  "shrine_gate",
  "mountain_view",
  "compass_check",
  "trail_marker",
  "rest_stop",
  "sunrise_climb",
  "cloud_pass",
  "summit_wave",
  "descent_path",
] as const;

const TRAINING_GROUNDS_VARIANTS = [
  "kana_training_stance",
  "kana_writing_practice",
  "kana_demonstration",
  "kana_scroll",
  "kana_brush",
  "kana_dojo_bow",
  "kana_card_drill",
  "kana_stroke_demo",
  "kana_pair_match",
  "vocab_holding_cards",
  "vocab_teaching_words",
  "vocab_word_wall",
  "vocab_flash_stack",
  "vocab_meaning_point",
  "vocab_review_desk",
  "vocab_pair_practice",
  "vocab_context_card",
  "vocab_recognition",
  "grammar_reading_scroll",
  "grammar_sentence_structure",
  "grammar_shrine_bow",
  "grammar_pattern_board",
  "grammar_example_point",
  "grammar_particle_demo",
  "grammar_conjugation",
  "grammar_compare_scrolls",
  "grammar_explain_shrine",
  "listening_headphones",
  "listening_careful",
  "listening_note_take",
  "listening_audio_focus",
  "listening_pavilion_rest",
  "listening_repeat_gesture",
  "listening_comprehension",
  "listening_waveform",
  "listening_pair_practice",
  "listening_pavilion_bow",
  "training_welcome",
  "training_hub_wave",
  "training_mastery_pose",
] as const;

const SEASONAL_VARIANTS = [
  "spring_cherry_blossom",
  "spring_petal_rain",
  "spring_picnic",
  "spring_trail_bloom",
  "spring_festival_lantern",
  "summer_festival_clothing",
  "summer_festival_fan",
  "summer_fireworks",
  "summer_heat_rest",
  "summer_stream",
  "autumn_falling_leaves",
  "autumn_maple_trail",
  "autumn_harvest",
  "autumn_warm_scarf",
  "autumn_moon_view",
  "winter_snow_gear",
  "winter_snowfall",
  "winter_hot_tea",
  "winter_ice_trail",
  "winter_new_year",
] as const;

const REWARD_VARIANTS = [
  "opening_treasure_chest",
  "holding_xp_reward",
  "holding_achievement_badge",
  "presenting_reward",
  "chest_glow",
  "xp_sparkle",
  "badge_present",
  "collectible_reveal",
  "reward_fanfare",
  "loot_spread",
  "milestone_gift",
  "trail_treasure",
  "summit_reward",
  "quest_payout",
  "daily_bonus",
  "streak_bonus",
  "level_reward",
  "shop_unwrap",
  "chest_key_turn",
  "reward_celebration",
] as const;

function createPack(
  id: YamaExpressionPackId,
  label: string,
  expression: YamaExpression,
  minimumVariations: number,
  useCases: readonly string[],
  variants: readonly string[],
  fallbackExpression?: YamaExpression,
): YamaAssetPack {
  const assets = buildPlannedPackAssets(id, variants, fallbackExpression);
  return {
    id,
    label,
    expression,
    minimumVariations,
    useCases,
    variants,
    assets,
  };
}

export const YAMA_EXPRESSION_PACKS: Record<YamaExpressionPackId, YamaAssetPack> = {
  happy: createPack(
    "happy",
    "Happy",
    "happy",
    10,
    ["Lesson completion", "Correct answers", "Daily goals"],
    HAPPY_VARIANTS,
  ),
  celebrating: createPack(
    "celebrating",
    "Celebrating",
    "celebrating",
    15,
    ["Checkpoint completion", "Region completion", "Achievement unlocks"],
    CELEBRATING_VARIANTS,
  ),
  encouraging: createPack(
    "encouraging",
    "Encouraging",
    "encouraging",
    10,
    ["Returning users", "Daily reminders", "Low motivation"],
    ENCOURAGING_VARIANTS,
  ),
  thinking: createPack(
    "thinking",
    "Thinking",
    "thinking",
    15,
    ["Hints", "Explanations", "Grammar lessons", "Reading tips"],
    THINKING_VARIANTS,
  ),
  teaching: createPack(
    "teaching",
    "Teaching",
    "teaching",
    15,
    ["Lesson introductions", "Tutorials", "Checkpoint instructions"],
    TEACHING_VARIANTS,
    "thinking",
  ),
  surprised: createPack(
    "surprised",
    "Surprised",
    "surprised",
    10,
    ["Rare achievements", "Unexpected events", "Easter eggs"],
    SURPRISED_VARIANTS,
    "happy",
  ),
  concerned: createPack(
    "concerned",
    "Concerned",
    "concerned",
    10,
    ["Long inactivity", "Repeated mistakes", "Lost streaks"],
    CONCERNED_VARIANTS,
    "encouraging",
  ),
  determined: createPack(
    "determined",
    "Determined",
    "determined",
    15,
    ["Boss challenges", "Exams", "Regional trials"],
    DETERMINED_VARIANTS,
    "victorious",
  ),
  sleeping: createPack(
    "sleeping",
    "Sleeping",
    "sleeping",
    10,
    ["Night events", "Idle states", "Offline periods"],
    SLEEPING_VARIANTS,
    "loading",
  ),
  confused: createPack(
    "confused",
    "Confused",
    "confused",
    10,
    ["User errors", "Unexpected situations", "Hint moments"],
    CONFUSED_VARIANTS,
  ),
  sad: createPack(
    "sad",
    "Sad",
    "sad",
    10,
    ["Lost streaks", "Failed challenges"],
    SAD_VARIANTS,
    "supportive",
  ),
  adventure: createPack(
    "adventure",
    "Adventure",
    "adventure",
    30,
    ["Journey map", "Region travel", "Exploration"],
    ADVENTURE_VARIANTS,
    "main",
  ),
  training_grounds: createPack(
    "training_grounds",
    "Training Grounds",
    "training",
    40,
    ["Kana Dojo", "Vocabulary Hall", "Grammar Shrine", "Listening Pavilion"],
    TRAINING_GROUNDS_VARIANTS,
    "studying",
  ),
  seasonal: createPack(
    "seasonal",
    "Seasonal",
    "seasonal",
    20,
    ["Spring", "Summer", "Autumn", "Winter events"],
    SEASONAL_VARIANTS,
    "happy",
  ),
  reward: createPack(
    "reward",
    "Reward",
    "reward",
    20,
    ["Treasure chests", "XP rewards", "Achievement badges"],
    REWARD_VARIANTS,
    "celebrating",
  ),
};

export const YAMA_ASSET_CATALOG: readonly YamaAssetEntry[] = Object.values(
  YAMA_EXPRESSION_PACKS,
).flatMap((pack) => pack.assets);

/** Shipped expression assets (legacy ids in public/mascots). */
export const YAMA_SHIPPED_ASSETS: readonly YamaAssetEntry[] = [
  {
    id: "yama_main_light_v1",
    packId: "happy",
    variant: "neutral",
    theme: "light",
    version: 1,
    status: "approved",
    publicPath: APPROVED_PUBLIC_PATHS.yama_main_light_v1,
  },
  {
    id: "yama_main_dark_v1",
    packId: "happy",
    variant: "neutral",
    theme: "dark",
    version: 1,
    status: "approved",
    publicPath: APPROVED_PUBLIC_PATHS.yama_main_dark_v1,
  },
  {
    id: "yama_happy_light_v1",
    packId: "happy",
    variant: "small_smile",
    theme: "light",
    version: 1,
    status: "approved",
    publicPath: APPROVED_PUBLIC_PATHS.yama_happy_light_v1,
  },
  {
    id: "yama_happy_dark_v2",
    packId: "happy",
    variant: "small_smile",
    theme: "dark",
    version: 2,
    status: "approved",
    publicPath: APPROVED_PUBLIC_PATHS.yama_happy_dark_v2,
  },
  {
    id: "yama_celebrating_light_v1",
    packId: "celebrating",
    variant: "victory_pose",
    theme: "light",
    version: 1,
    status: "approved",
    publicPath: APPROVED_PUBLIC_PATHS.yama_celebrating_light_v1,
  },
  {
    id: "yama_celebrating_dark_v2",
    packId: "celebrating",
    variant: "victory_pose",
    theme: "dark",
    version: 2,
    status: "approved",
    publicPath: APPROVED_PUBLIC_PATHS.yama_celebrating_dark_v2,
  },
  {
    id: "yama_encouraging_light_v1",
    packId: "encouraging",
    variant: "gentle_smile",
    theme: "light",
    version: 1,
    status: "approved",
    publicPath: APPROVED_PUBLIC_PATHS.yama_encouraging_light_v1,
  },
  {
    id: "yama_encouraging_dark_v2",
    packId: "encouraging",
    variant: "gentle_smile",
    theme: "dark",
    version: 2,
    status: "approved",
    publicPath: APPROVED_PUBLIC_PATHS.yama_encouraging_dark_v2,
  },
  {
    id: "yama_thinking_light_v1",
    packId: "thinking",
    variant: "hand_on_chin",
    theme: "light",
    version: 1,
    status: "approved",
    publicPath: APPROVED_PUBLIC_PATHS.yama_thinking_light_v1,
  },
  {
    id: "yama_thinking_dark_v2",
    packId: "thinking",
    variant: "hand_on_chin",
    theme: "dark",
    version: 2,
    status: "approved",
    publicPath: APPROVED_PUBLIC_PATHS.yama_thinking_dark_v2,
  },
  {
    id: "yama_loading_light_v1",
    packId: "sleeping",
    variant: "waiting",
    theme: "light",
    version: 1,
    status: "approved",
    publicPath: APPROVED_PUBLIC_PATHS.yama_loading_light_v1,
    fallbackExpression: "loading",
  },
  {
    id: "yama_loading_dark_v2",
    packId: "sleeping",
    variant: "waiting",
    theme: "dark",
    version: 2,
    status: "approved",
    publicPath: APPROVED_PUBLIC_PATHS.yama_loading_dark_v2,
    fallbackExpression: "loading",
  },
  {
    id: "yama_victorious_light_v1",
    packId: "determined",
    variant: "victory",
    theme: "light",
    version: 1,
    status: "approved",
    publicPath: APPROVED_PUBLIC_PATHS.yama_victorious_light_v1,
    fallbackExpression: "victorious",
  },
  {
    id: "yama_victorious_dark_v1",
    packId: "determined",
    variant: "victory",
    theme: "dark",
    version: 1,
    status: "approved",
    publicPath: APPROVED_PUBLIC_PATHS.yama_victorious_dark_v1,
    fallbackExpression: "victorious",
  },
  {
    id: "yama_confused_light_v1",
    packId: "confused",
    variant: "tilted_head",
    theme: "light",
    version: 1,
    status: "approved",
    publicPath: APPROVED_PUBLIC_PATHS.yama_confused_light_v1,
  },
  {
    id: "yama_confused_dark_v1",
    packId: "confused",
    variant: "tilted_head",
    theme: "dark",
    version: 1,
    status: "approved",
    publicPath: APPROVED_PUBLIC_PATHS.yama_confused_dark_v1,
  },
  {
    id: "yama_teaching_pointing_board_dark_v1",
    packId: "teaching",
    variant: "pointing_board",
    theme: "dark",
    version: 1,
    status: "approved",
    publicPath: APPROVED_PUBLIC_PATHS.yama_teaching_pointing_board_dark_v1,
  },
  {
    id: "yama_teaching_pointing_board_light_v1",
    packId: "teaching",
    variant: "pointing_board",
    theme: "light",
    version: 1,
    status: "approved",
    publicPath: APPROVED_PUBLIC_PATHS.yama_teaching_pointing_board_light_v1,
  },
  {
    id: "yama_surprised_wide_eyes_dark_v1",
    packId: "surprised",
    variant: "wide_eyes",
    theme: "dark",
    version: 1,
    status: "approved",
    publicPath: APPROVED_PUBLIC_PATHS.yama_surprised_wide_eyes_dark_v1,
  },
  {
    id: "yama_surprised_wide_eyes_light_v1",
    packId: "surprised",
    variant: "wide_eyes",
    theme: "light",
    version: 1,
    status: "approved",
    publicPath: APPROVED_PUBLIC_PATHS.yama_surprised_wide_eyes_light_v1,
  },
  {
    id: "yama_concerned_supportive_concern_dark_v1",
    packId: "concerned",
    variant: "supportive_concern",
    theme: "dark",
    version: 1,
    status: "approved",
    publicPath: APPROVED_PUBLIC_PATHS.yama_concerned_supportive_concern_dark_v1,
  },
  {
    id: "yama_concerned_supportive_concern_light_v1",
    packId: "concerned",
    variant: "supportive_concern",
    theme: "light",
    version: 1,
    status: "approved",
    publicPath: APPROVED_PUBLIC_PATHS.yama_concerned_supportive_concern_light_v1,
  },
  {
    id: "yama_determined_ready_stance_dark_v1",
    packId: "determined",
    variant: "ready_stance",
    theme: "dark",
    version: 1,
    status: "approved",
    publicPath: APPROVED_PUBLIC_PATHS.yama_determined_ready_stance_dark_v1,
  },
  {
    id: "yama_determined_ready_stance_light_v1",
    packId: "determined",
    variant: "ready_stance",
    theme: "light",
    version: 1,
    status: "approved",
    publicPath: APPROVED_PUBLIC_PATHS.yama_determined_ready_stance_light_v1,
  },
  {
    id: "yama_sleeping_resting_dark_v1",
    packId: "sleeping",
    variant: "resting",
    theme: "dark",
    version: 1,
    status: "approved",
    publicPath: APPROVED_PUBLIC_PATHS.yama_sleeping_resting_dark_v1,
  },
  {
    id: "yama_sleeping_resting_light_v1",
    packId: "sleeping",
    variant: "resting",
    theme: "light",
    version: 1,
    status: "approved",
    publicPath: APPROVED_PUBLIC_PATHS.yama_sleeping_resting_light_v1,
  },
  {
    id: "yama_sad_supportive_disappointed_dark_v1",
    packId: "sad",
    variant: "supportive_disappointed",
    theme: "dark",
    version: 1,
    status: "approved",
    publicPath: APPROVED_PUBLIC_PATHS.yama_sad_supportive_disappointed_dark_v1,
  },
  {
    id: "yama_sad_supportive_disappointed_light_v1",
    packId: "sad",
    variant: "supportive_disappointed",
    theme: "light",
    version: 1,
    status: "approved",
    publicPath: APPROVED_PUBLIC_PATHS.yama_sad_supportive_disappointed_light_v1,
  },
  {
    id: "yama_adventure_hiking_dark_v1",
    packId: "adventure",
    variant: "hiking",
    theme: "dark",
    version: 1,
    status: "approved",
    publicPath: APPROVED_PUBLIC_PATHS.yama_adventure_hiking_dark_v1,
  },
  {
    id: "yama_adventure_hiking_light_v1",
    packId: "adventure",
    variant: "hiking",
    theme: "light",
    version: 1,
    status: "approved",
    publicPath: APPROVED_PUBLIC_PATHS.yama_adventure_hiking_light_v1,
  },
  {
    id: "yama_training_demo_stance_dark_v1",
    packId: "training_grounds",
    variant: "demo_stance",
    theme: "dark",
    version: 1,
    status: "approved",
    publicPath: APPROVED_PUBLIC_PATHS.yama_training_demo_stance_dark_v1,
  },
  {
    id: "yama_training_demo_stance_light_v1",
    packId: "training_grounds",
    variant: "demo_stance",
    theme: "light",
    version: 1,
    status: "approved",
    publicPath: APPROVED_PUBLIC_PATHS.yama_training_demo_stance_light_v1,
  },
  {
    id: "yama_seasonal_cherry_blossom_dark_v1",
    packId: "seasonal",
    variant: "cherry_blossom",
    theme: "dark",
    version: 1,
    status: "approved",
    publicPath: APPROVED_PUBLIC_PATHS.yama_seasonal_cherry_blossom_dark_v1,
  },
  {
    id: "yama_seasonal_cherry_blossom_light_v1",
    packId: "seasonal",
    variant: "cherry_blossom",
    theme: "light",
    version: 1,
    status: "approved",
    publicPath: APPROVED_PUBLIC_PATHS.yama_seasonal_cherry_blossom_light_v1,
  },
  {
    id: "yama_reward_presenting_badge_dark_v1",
    packId: "reward",
    variant: "presenting_badge",
    theme: "dark",
    version: 1,
    status: "approved",
    publicPath: APPROVED_PUBLIC_PATHS.yama_reward_presenting_badge_dark_v1,
  },
  {
    id: "yama_reward_presenting_badge_light_v1",
    packId: "reward",
    variant: "presenting_badge",
    theme: "light",
    version: 1,
    status: "approved",
    publicPath: APPROVED_PUBLIC_PATHS.yama_reward_presenting_badge_light_v1,
  },
];

export function getYamaAssetsByPack(
  packId: YamaExpressionPackId,
): readonly YamaAssetEntry[] {
  return YAMA_EXPRESSION_PACKS[packId]?.assets ?? [];
}

export function getApprovedYamaAssets(): readonly YamaAssetEntry[] {
  return YAMA_SHIPPED_ASSETS;
}

export function getPlannedYamaAssetCount(): number {
  return YAMA_ASSET_CATALOG.filter((asset) => asset.status === "planned").length;
}

export function buildYamaAssetId(
  packId: YamaExpressionPackId,
  variant: string,
  theme: YamaAssetTheme,
  version = 1,
): string {
  return buildAssetId(packId, variant, theme, version);
}
